In [14]:
import numpy as np

In [15]:
X = np.arange(-25,25).reshape((10,5))

In [16]:
ones = np.ones((np.shape(X)[0],1))

In [17]:
X_1 = np.append(X,ones,axis=1)
X_1

array([[-25., -24., -23., -22., -21.,   1.],
       [-20., -19., -18., -17., -16.,   1.],
       [-15., -14., -13., -12., -11.,   1.],
       [-10.,  -9.,  -8.,  -7.,  -6.,   1.],
       [ -5.,  -4.,  -3.,  -2.,  -1.,   1.],
       [  0.,   1.,   2.,   3.,   4.,   1.],
       [  5.,   6.,   7.,   8.,   9.,   1.],
       [ 10.,  11.,  12.,  13.,  14.,   1.],
       [ 15.,  16.,  17.,  18.,  19.,   1.],
       [ 20.,  21.,  22.,  23.,  24.,   1.]])

In [18]:
w = np.random.rand(np.shape(X_1)[1])

In [19]:
def predict(x, w):     
    total_stimulation = np.dot(x, w)       
    y_pred = 1 if total_stimulation > 0 else -1
    return y_pred    

In [20]:
y = np.array([1, -1, -1, 1, -1, 1, -1, -1, 1, -1])
eta = 0.01

In [21]:
for x, y_target in zip(X_1,y):
    y_predict = predict(x,w)
    delta_w = eta * (y_target - y_predict) * x
    w+=delta_w
    print(w)

[-0.28975473 -0.02806231  0.19660505 -0.11903341  0.0482152   0.38556506]
[0.11024527 0.35193769 0.55660505 0.22096659 0.3682152  0.36556506]
[0.11024527 0.35193769 0.55660505 0.22096659 0.3682152  0.36556506]
[-0.08975473  0.17193769  0.39660505  0.08096659  0.2482152   0.38556506]
[-0.08975473  0.17193769  0.39660505  0.08096659  0.2482152   0.38556506]
[-0.08975473  0.17193769  0.39660505  0.08096659  0.2482152   0.38556506]
[-0.18975473  0.05193769  0.25660505 -0.07903341  0.0682152   0.36556506]
[-0.38975473 -0.16806231  0.01660505 -0.33903341 -0.2117848   0.34556506]
[-0.08975473  0.15193769  0.35660505  0.02096659  0.1682152   0.36556506]
[-0.48975473 -0.26806231 -0.08339495 -0.43903341 -0.3117848   0.34556506]


In [25]:
epochs = 10
for e in range(epochs):
    for x, y_target in zip(X_1,y):
        y_predict = predict(x,w)
        delta_w = eta * (y_target - y_predict) * x
        w += delta_w
        print(w)

[-0.18975473 -0.04806231  0.05660505 -0.37903341 -0.3317848   0.26556506]
[ 0.21024527  0.33193769  0.41660505 -0.03903341 -0.0117848   0.24556506]
[ 0.21024527  0.33193769  0.41660505 -0.03903341 -0.0117848   0.24556506]
[ 0.01024527  0.15193769  0.25660505 -0.17903341 -0.1317848   0.26556506]
[ 0.01024527  0.15193769  0.25660505 -0.17903341 -0.1317848   0.26556506]
[ 0.01024527  0.17193769  0.29660505 -0.11903341 -0.0517848   0.28556506]
[-0.08975473  0.05193769  0.15660505 -0.27903341 -0.2317848   0.26556506]
[-0.08975473  0.05193769  0.15660505 -0.27903341 -0.2317848   0.26556506]
[0.21024527 0.37193769 0.49660505 0.08096659 0.1482152  0.28556506]
[-0.18975473 -0.04806231  0.05660505 -0.37903341 -0.3317848   0.26556506]
[-0.18975473 -0.04806231  0.05660505 -0.37903341 -0.3317848   0.26556506]
[ 0.21024527  0.33193769  0.41660505 -0.03903341 -0.0117848   0.24556506]
[ 0.21024527  0.33193769  0.41660505 -0.03903341 -0.0117848   0.24556506]
[ 0.01024527  0.15193769  0.25660505 -0.1790