In [171]:
import numpy as np

In [172]:
data = np.arange(5,30,2)

In [173]:
boolArr = data < 10

In [174]:
data[ (data <10) & (data > 20)]

array([], dtype=int32)

In [175]:
data = np.arange(24).reshape(4,6)

In [176]:
data

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [177]:
data[0,2:5]

array([2, 3, 4])

In [178]:
data[0:3,1]

array([ 1,  7, 13])

In [179]:
arr = np.arange(50).reshape(10,5)

In [180]:
split_level = 0.2
num_rows = arr.shape[0]
split_border = split_level * num_rows

In [181]:
X_train = arr[:round(split_border)]
X_test = arr[round(split_border):]

In [182]:
np.random.shuffle(arr)


In [183]:
X_train = arr[:round(split_border)]
X_test = arr[round(split_border):]

In [184]:
data = np.arange(500).reshape(100,5)

In [185]:
np.random.shuffle(data)

In [186]:
split_level = 0.2
num_rows = data.shape[0]
split_border = round(split_level * num_rows)

In [187]:
X_test = data[:split_border,:-1]
X_learn = data[split_border:,:-1]
y_test = data[:split_border,-1:]
y_learn = data[split_border:,-1:]