In [1]:
import numpy as np

In [3]:
data = np.array([[10, 7, 4], [3, 2, 1]])
data

array([[10,  7,  4],
       [ 3,  2,  1]])

In [4]:
data.mean()

4.5

In [9]:
data.mean(axis=0)


array([6.5, 4.5, 2.5])

In [10]:
data.mean(axis=1)

array([7., 2.])

In [13]:
np.average(data)

4.5

In [14]:
np.average(data,axis=0)

array([6.5, 4.5, 2.5])

In [15]:
np.average(data,axis=1)

array([7., 2.])

In [26]:
np.average(data, axis=1, weights=[0,1,1])

array([5.5, 1.5])

In [27]:
np.average(data,axis=1,weights=[2,3,5])

array([6.1, 1.7])